"""empty message

Revision ID: 3f2f061ee060
Revises: 
Create Date: 2017-05-06 12:53:44.625005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2f061ee060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menuName', sa.String(length=24), nullable=False),
    sa.Column('orderNo', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_menuName'), 'menus', ['menuName'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menuid', sa.Integer(), nullable=True),
    sa.Column('categoryName', sa.String(length=32), nullable=True),
    sa.Column('orderNo', sa.Integer(), nullable=True),
    sa.Column('visibled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['menuid'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_categoryName'), 'category', ['categoryName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_categoryName'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_menus_menuName'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
