"""empty message

Revision ID: 70b41ef36088
Revises: 3f1e013f570a
Create Date: 2017-05-13 12:00:48.994009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b41ef36088'
down_revision = '3f1e013f570a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_title', table_name='post')
    op.create_unique_constraint(None, 'post', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.create_index('ix_post_title', 'post', ['title'], unique=False)
    # ### end Alembic commands ###
